In [ ]:
import torch
print(torch.__version__)

2.0.0+cu118


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

^it means vector has 2 by 1 elements

In [ ]:
matrix = torch.tensor([[7, 8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
random_tensor = torch.rand(10, 10, 10)
random_tensor

tensor([[[2.5472e-01, 8.7973e-01, 1.9718e-01, 3.2452e-02, 6.6467e-01,
          9.5667e-01, 8.4114e-01, 6.4530e-01, 1.9954e-01, 1.8542e-01],
         [3.5824e-01, 6.1184e-01, 2.8954e-01, 1.4541e-01, 1.2747e-01,
          4.5043e-01, 2.2629e-01, 7.3308e-01, 5.3914e-01, 8.0920e-02],
         [2.0428e-01, 5.6059e-01, 8.4822e-02, 8.0738e-01, 1.0531e-01,
          9.2477e-01, 9.7959e-01, 2.5748e-01, 9.9720e-01, 4.1013e-01],
         [8.0538e-01, 5.0066e-01, 7.9963e-01, 6.9457e-01, 9.7548e-01,
          5.1531e-01, 2.2557e-01, 3.3011e-01, 4.2580e-01, 7.1304e-01],
         [1.7797e-01, 9.3191e-01, 8.7748e-01, 2.3180e-01, 1.4336e-01,
          4.0109e-01, 9.6913e-01, 8.8313e-01, 2.9903e-01, 8.4679e-01],
         [2.3637e-01, 4.9814e-01, 6.9650e-01, 8.3686e-01, 3.0214e-01,
          7.0545e-01, 5.5978e-01, 2.8063e-01, 9.0098e-01, 7.8329e-01],
         [3.0671e-01, 7.0037e-01, 1.5129e-01, 5.1763e-01, 9.3647e-01,
          9.0044e-01, 5.8034e-01, 9.0956e-01, 3.6664e-01, 6.2497e-01],
         [6.0

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([10, 10, 10])

In [ ]:
# random tensor w/ similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2176, 0.3917, 0.7183, 0.9708],
        [0.3140, 0.6747, 0.1342, 0.8025],
        [0.0759, 0.1479, 0.2953, 0.1331]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones*random_tensor

tensor([[0.2176, 0.3917, 0.7183, 0.9708],
        [0.3140, 0.6747, 0.1342, 0.8025],
        [0.0759, 0.1479, 0.2953, 0.1331]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(1, 11, 2) # start, end, step
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
zeros_like_one_to_ten = torch.zeros_like(input=one_to_ten)
zeros_like_one_to_ten

tensor([0, 0, 0, 0, 0])

**Note**: Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #datatypes torch.float16 or torch.float32 etc.
                               device = None, # such as cpu, cuda
                               requires_grad = False) # whether ot not track gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

**How to chanage datatype**

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting information from tensors (tensor attributes)

1. Tensors not right datatype - get datatype by tensor.dtype
2. Tensors not right shape - get shape by tensor.shape
3. Tensors not right device - get device by tensor.device


In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4013, 0.5751, 0.4062, 0.1614],
        [0.2614, 0.7522, 0.5075, 0.1055],
        [0.7103, 0.7272, 0.1793, 0.5551]])

In [ ]:
print(some_tensor)
print(f"Data type of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device Tensor is on: {some_tensor.device}")

tensor([[0.4013, 0.5751, 0.4062, 0.1614],
        [0.2614, 0.7522, 0.5075, 0.1055],
        [0.7103, 0.7272, 0.1793, 0.5551]])
Data type of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device Tensor is on: cpu


### Manipulating Tensors (tensor opeartions)

Tensor operation include:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix Multiplication

In [ ]:
# create a tensor and add 10 to it

tensor = torch.tensor([1, 2, 3])


In [ ]:
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
# you can use built-in function
torch.mul(tensor, 10)
torch.add(tensor, 10)
torch.sub(tensor, 10)

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of doing Multiplication in neural network and deep learning:

1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

In [ ]:
# element wise
print(f"{tensor} * {tensor} is: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) is: tensor([1, 4, 9])


In [ ]:
%%time
# matrix multipliaction
torch.matmul(tensor, tensor)

CPU times: user 323 µs, sys: 0 ns, total: 323 µs
Wall time: 715 µs


tensor(14)

In [ ]:
%%time
v = 0
for i in range(len(tensor)):
  v += tensor[i] * tensor[i]
print(v)

tensor(14)
CPU times: user 1.5 ms, sys: 0 ns, total: 1.5 ms
Wall time: 2.45 ms


In [ ]:
%%time
tensor @ tensor

CPU times: user 84 µs, sys: 15 µs, total: 99 µs
Wall time: 104 µs


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [ ]:
tensor_B.T, tensor_B.T.shape  # transpose

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)      #torch.mm is torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Finding the min max mean sum etc (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# mean function requires float datatypes
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

#Finding the positional min and max

In [ ]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [ ]:
a = x.argmax()
x[a], x

(tensor(90), tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping- reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute- return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# create a tensor

x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add a extra dimension
# x_reshaped = x.reshape(1, 9)
x.reshape(1, 9), x.reshape(9, 1), x.reshape(3, 3), x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
# x_stacked = torch.stack([x,x,x,x], dim=0)
torch.stack([x,x,x,x], dim=0), torch.stack([x,x,x,x], dim=1), x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Squeeze
x_reshaped = x.reshape(1, 9)

x_reshaped, x_reshaped.shape, x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
# Unsqueeze
x_squeeze = x_reshaped.squeeze()
x_squeeze, x_squeeze.shape, x_squeeze.unsqueeze(dim=0), x_squeeze.unsqueeze(dim=0).shape ,x_squeeze.unsqueeze(dim=1), x_squeeze.unsqueeze(dim=1).shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# torch.permute rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, channel]

# Permute the original tensor to rerrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)


x_permuted.shape, x_original.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [ ]:
# Permutino holds the same memory of original
x_original[0,0,0] = 72818
x_original[0,0,0], x_permuted[0,0,0]

(tensor(72818.), tensor(72818.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x, x[0], x[0,0], x[0,0,0]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [ ]:
x[:,:,2], x[0,2,2]

(tensor([[3, 6, 9]]), tensor(9))

## Pytorch tensors & Numpy

* Data in Numpy, want in PyTorch tensor -> torch.from_numoy(ndarray)
* PyTorch tensor -> Numpy -> torch.Tensor.numpy()

In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

numpy by default use float64 where as Pytorch tensor use float32
so when converting from numpy to pytorch, it by default uses the float64 datatypes unless it's specified otherwise.


In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# change the value of array

array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

So the array and tensor doesn't hold the same memory

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

So the array and tensor doesn't hold the same memory

## Reproductibility (trying to take random out of random)

to reduce the randomness we use **random seed**

In [ ]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A==random_tensor_B, random_tensor_A, random_tensor_B

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[0.2971, 0.3991, 0.9360, 0.1274],
         [0.4575, 0.5185, 0.0040, 0.4525],
         [0.0682, 0.1724, 0.6878, 0.8658]]),
 tensor([[0.3472, 0.4100, 0.2569, 0.2188],
         [0.9263, 0.8227, 0.0879, 0.0446],
         [0.5038, 0.0647, 0.3088, 0.2542]]))

In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D =  torch.rand(3, 4)

random_tensor_C == random_tensor_D, random_tensor_C, random_tensor_D

(tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

## Running tensors and PyTorch objects on GPU

In [ ]:
!nvidia-smi

Wed Apr 26 12:43:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# count number of devices

torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

the reason is GPU results in faster compuatation

In [ ]:
tensor = torch.tensor([1,2,3])

#tensor not on GPU
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to CPU for numpy

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])